# Generated by Django 5.1.5 on 2025-01-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(blank=True, choices=[('pt', 'Portugues'), ('en', 'Ingles')], default='pt', help_text='Book Language', max_length=2),
        ),
    ]
